formspree_form_id: formspree_form_id
name: FireStack
title: FireStack | News on CodeTorch, Project Tutorials, and More!
description: Welcome to FireStack! We go over everything going on CodeTorch,
  Including tutorials and much more!
tags:
  - codetorch
show_hero: true
menu:
  - title: Home
    url: /
  - title: Contact
    url: /contact
email: inferno@thectfiles.lol
disqus_username: firestack
